// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleCssNamespace {
    export interface IStyleCss {
        "accent-block": string;
        button: string;
        content: string;
        form: string;
        h1: string;
        header: string;
        home: string;
        input: string;
        logo: string;
        signature: string;
        video: string;
        "video-wrapper": string;
    }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss;

export = StyleCssModule;
