name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.16.2
      uses: actions/setup-node@v1
      with:
        node-version: 12.16.2
    - run: yarn
    - run: yarn build
    - name: Copy file via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH_KEY }}
      with:
        source: "./build/*"
        target: "/home/${{ secrets.USERNAME }}/"
    - run: rsync -va --delete-after /home/${{ secrets.USERNAME }}/build/ /var/www/blasswolf.com/html/